// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOuDyj8K6K8SGBLz2biG3bAR5GRp22Al8',
    appId: '1:768715571982:web:5ddcc422fee03f036a0d5f',
    messagingSenderId: '768715571982',
    projectId: 'medimate-704f1',
    authDomain: 'medimate-704f1.firebaseapp.com',
    storageBucket: 'medimate-704f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0eXRnJc2pqUQgvKLFDi_1YF2xhoBUgnc',
    appId: '1:768715571982:android:0619c8e991b870646a0d5f',
    messagingSenderId: '768715571982',
    projectId: 'medimate-704f1',
    storageBucket: 'medimate-704f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVt33BavBdLBsAF-SCb19CV57b2C5Ue0c',
    appId: '1:768715571982:ios:bd225052161d70086a0d5f',
    messagingSenderId: '768715571982',
    projectId: 'medimate-704f1',
    storageBucket: 'medimate-704f1.firebasestorage.app',
    iosBundleId: 'com.example.medimate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVt33BavBdLBsAF-SCb19CV57b2C5Ue0c',
    appId: '1:768715571982:ios:bd225052161d70086a0d5f',
    messagingSenderId: '768715571982',
    projectId: 'medimate-704f1',
    storageBucket: 'medimate-704f1.firebasestorage.app',
    iosBundleId: 'com.example.medimate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOuDyj8K6K8SGBLz2biG3bAR5GRp22Al8',
    appId: '1:768715571982:web:bff1966a4f7d393f6a0d5f',
    messagingSenderId: '768715571982',
    projectId: 'medimate-704f1',
    authDomain: 'medimate-704f1.firebaseapp.com',
    storageBucket: 'medimate-704f1.firebasestorage.app',
  );
}
